### ISSUE TITLE
How to call Login api with this pattern.

### ISSUE THREAD

**Issue by harrypatel07** [rgodlontonshaw/apicallsboss#2]
Hello,

First of all thanks for sharing this pattern.

This is a great pattern if I call the list view but how to manage the login screen with this pattern.

It means in the login screen, click of the login button call the API of login and get loading, success and error status?

Thanks

**Comment by rgodlontonshaw** [comment]
Hello @harrypatel07 ,

Pleasure, I was going to do another login API tutorial but I haven't really had time.

Please try something like this, which I have done in some apps.
In your ApiProvider class:
Future<LoginTokenResponse> login(String email, String password) async {
    var body = jsonEncode({'email': email, 'password': password});
    try {
      final response = await http.post((_baseUrl + 'api/login'),
          body: body,
          headers: {
            "Accept": "application/json",
            "content-type": "application/json"
          });
      if (response.statusCode == 200) {
        var responseJsonToken;
        responseJsonToken = _returnResponse(response);
        var token = LoginTokenResponse.fromJson(responseJsonToken);
        if (responseJsonToken != null) {
          final storage = FlutterSecureStorage();
          storage.write(key: 'token', value: token);
        } else {
          return null;
        }
        return token;
      } else {
        return null;
      }
    } on SocketException {
      return null;
    }
  }

Then on your login page:

ApiProvider _helper = ApiProvider();
bool _loading = false;

  void doLogin() async {
    if (_formKey.currentState.validate()) {
      setState(() => _loading = true);
      if (await _helper.login(_email.text, _password.text) == null) {
        setState(() => _loading = false);
        _showError(
            context, 'An error occurred while logging in, please try again.');
        _key.currentState
            .showSnackBar(SnackBar(content: Text("Could not login.")));
      } else {
        setState(() => _loading = false);
        Navigator.pushReplacement(
            context,
            MaterialPageRoute(
                builder: (BuildContext context) => AnotherScreen()));
      }
    }
  }

Hope this helps. ;)
